"use strict";try{(async()=>{try{const t="adneutral-cosmetic-critical";if(!document.getElementById(t)){const e=document.createElement("style");e.id=t,e.textContent=['iframe[src*="googlesyndication"]','iframe[src*="doubleclick.net"]','iframe[src*="googleadservices"]','iframe[src*="pagead2"]','iframe[src*="adthrive.com"]','[id*="google_ads_iframe"]','[id*="div-gpt-ad"]',"ins.adsbygoogle",'[id^="AdThrive_"]',".adthrive-ad",".adthrive-sticky-outstream",".adthrive-video-player",".adthrive-collapse",".raptive-ad-placement"].join(`,
`)+"{display:none!important;visibility:hidden!important;pointer-events:none!important;opacity:0!important;}",(document.head||document.documentElement).appendChild(e)}}catch{}let i;try{const t=chrome.runtime.getURL("rules/cosmetic_rules.json");i=await(await fetch(t)).json()}catch{return}let l;try{l=await chrome.storage.local.get("adneutral_settings")}catch{return}const m=l.adneutral_settings||{};if(m.masterEnabled===!1||m.universalAds===!1)return;function y(t){return[...new Set(t.filter(Boolean))]}const a=(location.hostname||"").replace(/^www\./,""),g=i.domains?.[a]||[],v=Object.entries(i.domains||{}).filter(([t])=>a===t||a.endsWith("."+t)).flatMap(([,t])=>t),u=y([...i.global||[],...g,...v]);if(!u.length)return;function b(t){const e=String(t).trim();if(!e||/:not\(\s*body\s*\)/i.test(e)&&/:not\(\s*html\s*\)/i.test(e))return e;const n=e.split("::"),f=`${n[0]}:not(body):not(html)`;return n.length>1?`${f}::${n.slice(1).join("::")}`:f}const r=u.map(b);function E(t){const e="adneutral-cosmetic-v2";let n=document.getElementById(e);n||(n=document.createElement("style"),n.id=e,(document.head||document.documentElement).appendChild(n));const o=t.join(`,
`)+` {
      display: none !important;
      visibility: hidden !important;
      pointer-events: none !important;
      height: 0 !important;
      min-height: 0 !important;
      max-height: 0 !important;
      overflow: hidden !important;
      opacity: 0 !important;
    }`;n.textContent=o}E(r);function c(t,e){try{e.forEach(n=>{try{t.querySelectorAll(n).forEach(o=>{o===document.body||o===document.documentElement||o.style.setProperty("display","none","important")})}catch{}})}catch{}}function s(t,e){try{t.querySelectorAll("*").forEach(n=>{n.shadowRoot&&(c(n.shadowRoot,e),s(n.shadowRoot,e))})}catch{}}let d=!1;const h=new MutationObserver(()=>{d||(d=!0,requestAnimationFrame(()=>{d=!1,c(document,r),s(document,r)}))});h.observe(document.documentElement||document.body,{childList:!0,subtree:!0});function p(){c(document,r),s(document,r)}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",p):p(),chrome.storage.onChanged.addListener((t,e)=>{if(e!=="local"||!t.adneutral_settings)return;const n=t.adneutral_settings.newValue||{};if(n.masterEnabled===!1||n.universalAds===!1){const o=document.getElementById("adneutral-cosmetic-v2");o&&o.remove();try{h.disconnect()}catch{}}})})()}catch(i){console.debug("[AdNeutral] cosmetic",i)}
